services:
  - type: web
    name: chronolette
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Chronolette
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "6543"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: supabase
      - key: SUPABASE_S3_KEY
        sync: false
      - key: SUPABASE_S3_SECRET
        sync: false
      - key: SUPABASE_S3_ENDPOINT
        sync: false
      - key: SUPABASE_S3_REGION
        value: us-east-1
      - key: SUPABASE_S3_BUCKET
        value: chronolette
      - key: SUPABASE_STORAGE_URL
        sync: false
      - key: MIGRATE_ON_START
        value: "true"
